
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:

title: Electronics for the Rest of Us!
description: INSPIRE 1A03 | Tharmeega Manimaran | May 2020 Intersession

theme: jekyll-theme-cayman
